### PR TITLE
Digikey v4 + Python3.12 + Digikey Localization

### PR DESCRIPTION
**Pull request by T0jan**
and some small bug fixes

### CODE REVIEW

**Comment by T0jan** [comment]
@eeintech Some of the parameter names have changed for the v4 Digi-Key API causing old cached data to not be usable anymore. At least that's the only case where I can reproduce the errors in the integration tests, so I assume cached data is used there? Do you have a way to update it?

**Comment by eeintech** [comment]
@T0jan Yes you're right, all the cache data for test sample parts is in [tests/files/results.tgz](https://github.com/sparkmicro/Ki-nTree/blob/345304ec49671de7e464588c1687f49ba1cfce2d/tests/files/results.tgz).
What you can is running the tests locally and update the `results.tgz` file with the new cache data.
Also, should we support both Digikey API v3 and v4? Was it your plan?

**Comment by T0jan** [comment]
@eeintech I don't really see a reason to support Digikey API v3 going forward. anyone with a user account can automatically use the v4 API and due to the different naming and structuring we would have to have two sets of code.

> We can also probably move away from Python 3.9 and only support 3.10 to 3.12.

Just for user convenience I would leave it in as long as it's still supported. EOL is next year.

**Comment by T0jan** [comment]
@eeintech from my side only the documentation of the rolling release stuff is missing now. However I noticed the Application window can't be dragged across the screen anymore on Ubuntu. Any idea why this could be?

**Comment by eeintech** [comment]
@T0jan Great effort here, looks like all CI tests are passing too!

Yeah it's my fault, I removed the top bar so now only the icon and text areas are draggable... I meant to make the full bar draggable with an extra container but got sidetracked, basically the green zone here is draggable:

image

This can be updated here: https://github.com/sparkmicro/Ki-nTree/blob/345304ec49671de7e464588c1687f49ba1cfce2d/kintree/gui/views/main.py#L39
Stretching a container all the way to the settings and quit buttons?

**Comment by T0jan** [comment]
@eeintech I extended the container somewhat hacky now, if you see a more elegant way, let me know.

**Comment by eeintech** [comment]
> I'm still wondering why the inventree authentication fails so often in the tests. maybe some kind of delay is needed to make sure the server is up before it want's to connect 🤔

Oh I see you ran it 3 times, yeah I'm not sure either it's quite annoying...

> @eeintech I extended the container somewhat hacky now, if you see a more elegant way, let me know.

As long as it works I'll be fine with it 😄
I'll do more review tomorrow

**Comment by eeintech** [comment]
Just realized the Settings view is missing the drag area and Close icon... not a big deal but we could add it too.

**Comment by eeintech** [comment]
## AutomationDirect

Works well with parts that exists in their database:
``` shell
[MAIN]  AutomationDirect search for PM-0112-020-0
[INFO]  No pricing attribute "ordering_attributes" found for "PM-0112-020-0"
```

But there is an KeyError exception thrown with other parts:
``` shell
[MAIN]  AutomationDirect search for 1234567890
Future exception was never retrieved
future: <Future finished exception=KeyError('price')>
Traceback (most recent call last):
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francois/development/Ki-nTree/.venv/lib/python3.12/site-packages/flet_core/page.py", line 944, in wrapper
    handler(*args)
  File "/home/francois/development/Ki-nTree/kintree/gui/views/main.py", line 454, in perform_pn_search
    self.run_search(e)
  File "/home/francois/development/Ki-nTree/kintree/gui/views/main.py", line 340, in run_search
    part_supplier_info = inventree_interface.supplier_search(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francois/development/Ki-nTree/kintree/database/inventree_interface.py", line 499, in supplier_search
    part_info = automationdirect_api.fetch_part_info(part_number)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francois/development/Ki-nTree/kintree/search/automationdirect_api.py", line 192, in fetch_part_info
    price_per_unit = part[price_key]
                     ~~~~^^^^^^^^^^^
KeyError: 'price'
```

## Digi-Key V4

It can't find part data, but I know those parts exist:
``` shell
[MAIN]  Digi-Key search for TL1105SF160Q
[INFO]  Error: Failed to fetch data for "TL1105SF160Q"

[MAIN]  Digi-Key search for RK73B1JTTD103J
[INFO]  Error: Failed to fetch data for "RK73B1JTTD103J"
```

This is my developer config:
image

## LCSC

An AttributeError exception is thrown:
``` shell
[MAIN]  LCSC search for C497902
[INFO]  Warning: API data download failed (HTTP Error)
Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francois/development/Ki-nTree/.venv/lib/python3.12/site-packages/flet_core/page.py", line 944, in wrapper
    handler(*args)
  File "/home/francois/development/Ki-nTree/kintree/gui/views/main.py", line 454, in perform_pn_search
    self.run_search(e)
  File "/home/francois/development/Ki-nTree/kintree/gui/views/main.py", line 340, in run_search
    part_supplier_info = inventree_interface.supplier_search(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francois/development/Ki-nTree/kintree/database/inventree_interface.py", line 493, in supplier_search
    part_info = lcsc_api.fetch_part_info(part_number)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francois/development/Ki-nTree/kintree/search/lcsc_api.py", line 69, in fetch_part_info
    part = part.get('result', None)
           ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by eeintech** [comment]
@T0jan For Digi-Key V4, I'm a little confused... the authentication works but then the part data received didn't match at all your changes in this PR... so I thought "it must be because it is getting data from the v3 API" so I created another app with only V4 enabled:

image

But then I'm getting authentication issues now:
``` shell
Exception when calling product_details_with_http_info: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 25 Oct 2024 20:21:46 GMT', 'Content-Type': 'application/json', 'Content-Length': '228', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '', 'Access-Control-Allow-Headers': 'origin, x-requested-with, accept, content-type, authorization,x-digikey-client-id, x-digikey-locale-site, x-digikey-locale-language, x-digikey-locale-currency, x-digikey-locale-shiptocountry, x-digikey-customer-id', 'Access-Control-Max-Age': '3628800', 'Access-Control-Allow-Methods': 'GET, POST', 'X-DIGIKEY-REQUEST-ID': 'be3c5a7d-c37b-48e7-8396-949e6c6855c4', 'Set-Cookie': 'TS012a951d=01460246b6f4313327ce3b5f931acf991d9d2efa9c77187afad62dd17aed54331614c4e3a640a9ab1e40d01eed313591c46d4a0397; Path=/; Secure; HTTPOnly'})
HTTP response body: {"ErrorResponseVersion":"3.0.0.0","StatusCode": 401,"ErrorMessage":"Invalid Client-Id","ErrorDetails":"X-DIGIKEY-Client-Id invalid for requested resource","RequestId":"be3c5a7d-c37b-48e7-8396-949e6c6855c4","ValidationErrors":[]}
```

If I add the older V3, this message disappears but the part data still don't match the processing.

This is the JSON data I get from a DK app with both V4 and V3 Product Information enabled: 
[digikey_v4.json](https://github.com/user-attachments/files/17527285/digikey_v4.json)

The format is V3 data, not V4.

So I really need to see you app configuration, because I'm not able to test it out so far 😄

**Comment by T0jan** [comment]
@eeintech have you updated the digikey-api to the 3.12 fork? On my setups I hadn't to change anything else for it to work basically out of the box. 

The other things seem easy to fix, but I probably will only get to it on Monday

**Comment by T0jan** [comment]
@eeintech in my 3.12 venv:

```
pip freeze | grep digikey
digikey-api @ https://github.com/hurricaneJoef/digikey-api/archive/refs/heads/master.zip#sha256=ed933c2e3607cb62a731e8df846deb222f8881636c898a5e70bedb7fc6cec437
```

interestingly the 3.10 venv reports it as the base version for some reason :thinking: 

```
pip freeze | grep digikey
digikey-api==1.0.0
```

So the only difference is you checked out a commit and I the branch, but that shouldn't make a difference. Have you tried to set up a new virtual environment and checked if it works there?

**Comment by T0jan** [comment]
a delay doesn't help :sweat_smile: 

the two other crashes and the drag bar for the settings view is done, still no idea what the digikey issue is tho.

**Comment by T0jan** [comment]
@eeintech ha I knew I forgot one of the requirements, should be fixed now.

> Not sure how you got there, this sha doesn't seem to exist in this repo?

The sha could be user specific, I got this by just using the link to the master.zip which is also in the requirements file:

```
pip uninstall digikey-api       # required as both package versions are tagged as v1.0.0 rn and then pip doesn't update them
pip install https://github.com/hurricaneJoef/digikey-api/archive/refs/heads/master.zip
```

Maybe there is a different handling of the `pyproject.toml` and `requirements.txt` or it#s an difference between windows pip and linux pip.

**Pull request merged**
