### PR TITLE
Add support for part query from TME

### PR DESCRIPTION
**Pull request by spike77453**
This adds support for part query from TME (Transfer Multisort Elektronik: https://www.tme.eu, headquartered in Poland).

kintree/search/tme_api.py is taken directly from https://github.com/sparkmicro/Ki-nTree/pull/115. I hope @martonmiklos doesn't mind.

I'm not entirely sure how to handle the dependency on https://github.com/krzych82/api-client-python3 here: 
https://github.com/sparkmicro/Ki-nTree/compare/main...spike77453:Ki-nTree:feature_tme_support?expand=1#diff-b2540e137995506e90ad635a1dbee24c1017fae8e8ade9e7da60628af46da9f8R6
Upstream neither provides a pypi release nor a `seutp.py` or `pyproject.toml` so it cannot be easily installed via pip, etc.

Feedback, pointers, and suggestions are welcome.

### CODE REVIEW

**Comment by martonmiklos** [comment]
> kintree/search/tme_api.py is taken directly from https://github.com/sparkmicro/Ki-nTree/pull/115. I hope @martonmiklos doesn't mind.

I am very glad to see this PR. I am stuck with tow broken and casted forearms, so I am grateful that you work on this.

> Upstream neither provides a pypi release nor a seutp.py or pyproject.toml so it cannot be easily installed via pip, etc.
> 
> Feedback, pointers, and suggestions are welcome.

I would simply add this as a submodule.

**Comment by spike77453** [comment]
> > kintree/search/tme_api.py is taken directly from #115. I hope @martonmiklos doesn't mind.
> 
> I am very glad to see this PR. I am stuck with tow broken and casted forearms, so I am grateful that you work on this.

Oh no. Get well soon!
 
> > Upstream neither provides a pypi release nor a seutp.py or pyproject.toml so it cannot be easily installed via pip, etc.
> > Feedback, pointers, and suggestions are welcome.
> 
> I would simply add this as a submodule.

Works for me. I've added it as a submodule.  
Just wasn't sure if that integrates well with the poetry build. There's also not license mentioned upstream (https://github.com/krzych82/api-client-python3) so as far as I'm aware that implies all rights are reserved.

**Comment by eeintech** [comment]
Thanks @spike77453 I will need to review this PR soon, in the meantime do you mind fixing the style?

**Comment by spike77453** [comment]
> in the meantime do you mind fixing the style?

Sure, style checks should now pass.

**Comment by eeintech** [comment]
Thanks for fixing the style.

Two things:
1. I cannot run the GUI anymore, I'm getting the same import error as in the CI:
``` shell
$ python -m kintree_gui
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/francois/development/Ki-nTree/kintree_gui.py", line 2, in <module>
    from kintree.kintree_gui import main
  File "/home/francois/development/Ki-nTree/kintree/kintree_gui.py", line 3, in <module>
    from .gui.gui import kintree_gui
  File "/home/francois/development/Ki-nTree/kintree/gui/gui.py", line 4, in <module>
    from .views.main import (
  File "/home/francois/development/Ki-nTree/kintree/gui/views/main.py", line 19, in <module>
    from ...database import inventree_interface
  File "/home/francois/development/Ki-nTree/kintree/database/inventree_interface.py", line 8, in <module>
    from ..search import search_api, digikey_api, mouser_api, element14_api, lcsc_api, tme_api
  File "/home/francois/development/Ki-nTree/kintree/search/tme_api.py", line 3, in <module>
    from .tme.tmeapi import Client
ModuleNotFoundError: No module named 'kintree.search.tme.tmeapi'```

2. I have looked into the submodule you'd like to use and everything is very generic code/project name and there is no license on this project... Can you ask the maintainer if we can port his code into Ki-nTree instead of adding it as submodule? Else we can also develop the same code, it is very simple.

**Comment by spike77453** [comment]
> I cannot run the GUI anymore, I'm getting the same import error as in the CI:

Did you [initialise the submodule](https://git-scm.com/docs/git-submodule) or clone the branch with `--recurse-submodules`, e.g.

```
git clone --recurse-submodules --branch feature_tme_support https://github.com/spike77453/Ki-nTree/
```

That should work just fine.

> I have looked into the submodule you'd like to use and everything is very generic code/project name and there is no license on this project... Can you ask the maintainer if we can port his code into Ki-nTree instead of adding it as submodule? Else we can also develop the same code, it is very simple.

I'll open an issue at https://github.com/krzych82/api-client-python3 and ask.  
It also does some nasty things: https://github.com/sparkmicro/Ki-nTree/pull/164/files#diff-b2540e137995506e90ad635a1dbee24c1017fae8e8ade9e7da60628af46da9f8R50-R52 so I'm not all opposed to writing something similar.

**Comment by eeintech** [comment]
@spike77453 Following up on that, did you ask the owner of the package if it's fine to use his code and/or rewrite it?

**Comment by martonmiklos** [comment]
> @spike77453 Following up on that, did you ask the owner of the package if it's fine to use his code and/or rewrite it?

Request had been made:
https://github.com/krzych82/api-client-python3/issues/3
however @krzych82 have not responded yet.

However it seems that there is a code with similar functionality in this repo which has proper licensing:
https://github.com/tme-dev/TME-API/blob/master/Python/call.py

Maybe it would be easier to port to this?

**Comment by krzych82** [comment]
Hi.
License added. You can feel free to use and rewrite it.

**Comment by eeintech** [comment]
@krzych82 Ok good, can you pull the `main` branch in, then I'll rerun the CI 👍

**Comment by spike77453** [comment]
> @spike77453 Can you please pull the `main` branch in, then I'll rerun the CI 👍

@eeintech I've updated the submodule to its remote master (to include the license file) and rebased this feature branch to main. Let me know if that works for you.

**Comment by eeintech** [comment]
@spike77453 The GUI is still failing to run, try to store the file inside the project in in this case? I'd rather that option than a submodule. Thanks!

**Comment by spike77453** [comment]
I've opted to reimplement the functionality of https://github.com/krzych82/api-client-python3. The API examples/snippets TME give in [their documentation](https://developers.tme.eu/documentation/download) are MIT licensed (https://github.com/tme-dev/TME-API/blob/master/Python/call.py) so that should be fine.

Hope that works for you.

**Comment by eeintech** [comment]
@spike77453 Works for me! There still is an error in the CI:

``` shell
Traceback (most recent call last):
  File "/home/runner/work/Ki-nTree/Ki-nTree/kintree_gui.py", line 2, in <module>
    from kintree.kintree_gui import main
  File "/home/runner/work/Ki-nTree/Ki-nTree/kintree/kintree_gui.py", line 3, in <module>
    from .gui.gui import kintree_gui
  File "/home/runner/work/Ki-nTree/Ki-nTree/kintree/gui/gui.py", line 10, in <module>
    from .views.settings import (
  File "/home/runner/work/Ki-nTree/Ki-nTree/kintree/gui/views/settings.py", line 87, in <module>
    tme_api_settings['TME_API_TOKEN'],
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.
```

**Comment by spike77453** [comment]
I'm afraid that's nothing I can fix. You'd have to specify an API token, probably via an encrypted secret: https://github.com/sparkmicro/Ki-nTree/blob/main/.github/workflows/test_deploy.yaml#L43-L53

**Comment by eeintech** [comment]
@spike77453 I think the right syntax would be: `tme_api_settings.get('TME_API_TOKEN', '')` and same for others

**Comment by spike77453** [comment]
My bad! I added default configuration files but forgot to load them in: https://github.com/sparkmicro/Ki-nTree/compare/e8a20dd8c7caa95673c3ec8da173892d0752275d..822f0ef1703c47081e062c83bb781e718e1de302
Should be ok now.

**Comment by eeintech** [comment]
Great, thanks @spike77453 I'll prepare a new release

**Pull request merged**
