### PR TITLE
[WIP]Add support for part query from TME

### PR DESCRIPTION
**Pull request by martonmiklos**
@eeintech 
in the #87 this topic came up and I would rather continue the discussion here to prevent off-topic:

> @martonmiklos What is TME? Happy to discuss it +1

TME is a polish supplier company for electrical parts. They have a quite comprehensive json based API.

The thing what I wanted to discuss (and why I started to work on the category selection) is the fact that they have a quite usable and localized! category tree which could be accessed via their API (~1500 categories).

For new InvenTree users (like me) it could be a reasonable action to pull their category tree. 

I have implemented it in a dumb manner: I added a button to the TME settings, it retrieve the category tree and create all categories:
kép

During the process it blocks the UI at the moment.
What do you think about including this feature into Ki-n-tree?

As this feature for me was a one-shot thing I can remove it from the PR.
If you have willing to accept it I would like to sophisticate it with a messagebox saying something like:
```
This operation is going to copy the TME category tree into the InvenTree.
This means it going to create ~1500 or more categories, which is likely going to take long time.
The UI might be frozen during the operation, do you want to continue?
```

### CODE REVIEW

**Comment by eeintech** [comment]
Oh I see what "TME" means now, I'm okay adding another supplier.
I was actually thinking that the supplier side of things is not really re-usable... should have created classes instead.
It works for now but it's not clean code. Anyway, for another day.

I understand the idea behind the create categories button, I will have to think about it as not everybody wants to setup their database the way we do, I am leaning towards not worrying about setting it up and leave this up to the users. However the really important part is to pull/sync all the categories from InvenTree and not rely on static/manual setup for adding parts.
My thinking was to add a "Update Categories" button actually to trigger the sync manually and hang the GUI every single time a part is added (categories are not things that change much over time).

**Comment by eeintech** [comment]
@martonmiklos I'm currently working on `1.0.0` release. I think `0.6.6` will be the last release with the current UI, while `1.0.0` will feature a complete new UI made with [Flet](https://github.com/flet-dev/flet).
Would you mind waiting for the switch then re-implementing it in the new UI? Sorry about this, and if I made you waste your time :worried:

**Comment by martonmiklos** [comment]
>  a complete new UI made with [Flet](https://github.com/flet-dev/flet). Would you mind waiting for the switch then re-implementing it in the new UI? 

Ah I wanted to bitching about replacing pysimpleui with PyQt before (I found the pysimpleui very problematic for more complex UI things). Anyway I will take a look on this Flet and get back. I have to admit that I am lacking of free time nowadays which negatively affect my contributions around InvenTree...

**Comment by eeintech** [comment]
No problem, after trying Flet I'm not going back to PySimpleGUI for sure, this is soooo much better for building desktop/mobile apps!

**Pull request closed without merging**
