### PR TITLE
1.1.0

### LINKED ISSUE #202: Coverage is not following new releases
Coverage badge is out of date: 
image

Coveralls website is still on v1 RC release: https://coveralls.io/github/sparkmicro/Ki-nTree?branch=main

### LINKED ISSUE #217: KeyError 'parameters' when updating a component in/to inventree
kintree 1.0.7 (windows)

trying to update a component from lcsc creates this error with inventree 0.14.1

`[MAIN]  Searching for original part in database←[0m
←[92m[INFO] Success: Found original part in database (ID = 234 | Description = "TSSOP-20  ADC/DAC - Specialized ROHS")←[0m
←[93m[INFO]     Warning: The following parameters were not found in supplier data:
['Clock Frequency', 'Speed', 'Data Rate', 'Frequency Range', '-3db Bandwidth', 'Translator Type', 'Technology', 'Core Processor', 'Type', 'Sensor Type', 'Program Memory Size', 'Memory Size', 'Channels per Circuit', 'Package / Case', 'Voltage - VCCA', 'Voltage - VCCB', 'Voltage - Supply', 'Voltage - Supply (Vcc/Vdd)', 'Voltage - Supply, Digital', 'Voltage - Supply, Single (V+)', 'Operating Temperature']←[0m
Exception in thread Thread-174 (create_part):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\kintree\gui\views\main.py", line 1380, in create_part
    alt_result = inventree_interface.inventree_create_alternate(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\kintree\database\inventree_interface.py", line 813, in inventree_create_alternate
    inventree_part = translate_form_to_inventree(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\kintree\database\inventree_interface.py", line 357, in translate_form_to_inventree
    for search_param in part_info['parameters'].keys():
                        ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'parameters'
`

kintree 1.0.4 (ubuntu 20.04 - running in WSL on windows) (for some reason it wont upgrade using pip install kintree --upgrade)


`[MAIN]  Searching for original part in database
[INFO] Success: Found original part in database (ID = 234 | Description = "TSSOP-20  ADC/DAC - Specialized ROHS")
[INFO]  Warning: The following parameters were not found in supplier data:
['Clock Frequency', 'Speed', 'Data Rate', 'Frequency Range', '-3db Bandwidth', 'Translator Type', 'Technology', 'Core Processor', 'Type', 'Sensor Type', 'Program Memory Size', 'Memory Size', 'Channels per Circuit', 'Package / Case', 'Voltage - VCCA', 'Voltage - VCCB', 'Voltage - Supply', 'Voltage - Supply (Vcc/Vdd)', 'Voltage - Supply, Digital', 'Voltage - Supply, Single (V+)', 'Operating Temperature']
Exception in thread Thread-105:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/kintree/gui/views/main.py", line 1268, in create_part
    alt_result = inventree_interface.inventree_create_alternate(
  File "/home/user/.local/lib/python3.8/site-packages/kintree/database/inventree_interface.py", line 739, in inventree_create_alternate
    inventree_part = translate_form_to_inventree(
  File "/home/user/.local/lib/python3.8/site-packages/kintree/database/inventree_interface.py", line 313, in translate_form_to_inventree
    for search_param in part_info['parameters'].keys():
KeyError: 'parameters'
`

### PR DESCRIPTION
**Pull request by eeintech**
- #219 
- Fixes #217 
- Should fix #202 
- Update `flet` package to latest version #224 
- Incorporated #223 here directly as new `flet` version broke it
- Update README and add note in the docs about #225

### CODE REVIEW

**Comment by eeintech** [comment]
@T0jan Updating `inventree` to `0.13.x` seems to brake the automated setup but I'm not sure why... given you're more up to date on Inventree than I am, would you know why?

**Comment by T0jan** [comment]
weird one, I have no problems connecting to different InvenTree servers with inventree-0.13.3 and Python3.11. The only instances where I can reproduce the error is by providing a wrong address/credentials or when the server is down. 

So I think something goes wrong in the github-job, either while setting up the server or by it then providing an interface, even tho the log looks identical to 3.9 and 3.10 until it fails. Maybe there is a problem with 3.11 and the latest stable InvenTree commit?

**Comment by T0jan** [comment]
not sure how I made it worse xD

**Comment by eeintech** [comment]
> not sure how I made it worse xD

The test Digi-Key token expired, it happens often. I refreshed it and restarted the CI, let's see

**Comment by eeintech** [comment]
@T0jan Now both Python `3.9` and `3.10` fail but `3.11` is fine 🤣 It is so confusing...

**Comment by T0jan** [comment]
rerun of 3.10 worked now and 3.99 again fails due to Digi-Key API, so I call github job problems here.

**Comment by G-Pereira** [comment]
Is it an issue of having too frequent digikey API requests?

**Comment by eeintech** [comment]
> rerun of 3.10 worked now and 3.9 again fails due to Digi-Key API, so I call github job problems here.

Refreshed token, let's see but I am on your side thinking it is a false positive, maybe something changed on Github's side between different jobs which we are not aware of...

> Is it an issue of having too frequent digikey API requests?

Shouldn't be for a normal user

**Pull request merged**
