### PR TITLE
Upgrade flet version to latest

### PR DESCRIPTION
**Pull request by eeintech**

### CODE REVIEW

**Comment by eeintech** [comment]
@T0jan Mind telling me if you find any issue with this branch? Intent is to upgrade the flet version to the latest

**Comment by T0jan** [comment]
@eeintech I assume you rebuilt it for flet-0.22.0? They seem to have included a lot of libraries since 0.19.0 which can't be easily installed on non-debian/fedora linux which is certainly a choice. As I am using Arch privately I was only able to get Ki-nTree running with flet-0.19.0 but it doesn't show anything in the window except the top bar. I will try to check on my work machines next week, where I have more mainstream OS to work with.

**Comment by second-string** [comment]
I pulled this and built it locally on macOS and everything looks solid at first glance.
Bildschirmfoto 2024-04-20 um 21 24 30
I have to actually figure out how to set up the connections and whatnot to use the functionality but let me know if you want me to test anything specific.

**Comment by eeintech** [comment]
> @eeintech I assume you rebuilt it for flet-0.22.0? They seem to have included a lot of libraries since 0.19.0 which can't be easily installed on non-debian/fedora linux which is certainly a choice. As I am using Arch privately I was only able to get Ki-nTree running with flet-0.19.0 but it doesn't show anything in the window except the top bar. I will try to check on my work machines next week, where I have more mainstream OS to work with.

For Flet `0.19` and older the `build` methods of views was called `_build` therefore the views won't be constructed with this branch as never called. Mainstream OS would be nice to test with as I'm not familiar with Arch linux and the issues with latest Flet versions.

> I have to actually figure out how to set up the connections and whatnot to use the functionality but let me know if you want me to test anything specific.

@second-string Thanks please let me know if you find anything weird after setting up the full part creation flow 👍

**Review by T0jan — CHANGES_REQUESTED** [review]
There is some issue here, confirmed on windows, ubuntu 20 and ubuntu 22:

https://github.com/sparkmicro/Ki-nTree/blob/96771e94132c018b5ba453fec4ddb6205b054fa9/kintree/gui/views/main.py#L151-L156

As soon as I try to search for a second part (or the same part on a different supplier) there is an unrecoverable UI crash:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "~/.local/lib/python3.10/site-packages/flet_core/page.py", line 528, in wrapper
    handler(*args)
  File "~/workspace/github/Ki-nTree/kintree/gui/views/main.py", line 300, in run_search
    self.reset_view(e, ignore=['part_number', 'supplier'])
  File "~/workspace/github/Ki-nTree/kintree/gui/views/main.py", line 289, in reset_view
    return super().reset_view(e, ignore=ignore, hidden=hidden_fields)
  File "~/workspace/github/Ki-nTree/kintree/gui/views/main.py", line 162, in reset_view
    reset_field(value)
  File "~/workspace/github/Ki-nTree/kintree/gui/views/main.py", line 156, in reset_field
    field.update()
  File "~/.local/lib/python3.10/site-packages/flet_core/control.py", line 293, in update
    assert self.__page, "Control must be added to the page first."
AssertionError: Control must be added to the page first.
```
----
Linux installations need an additional package to be installed before flet>0.19 can work, for debian based systems the package is covered by APT:

`sudo apt -y install libmpv1`

----
The Inventree API should be updated also to the latest version (13.3, have checked all functions and found no issues):

https://github.com/sparkmicro/Ki-nTree/blob/96771e94132c018b5ba453fec4ddb6205b054fa9/requirements.txt#L4

**Comment by second-string** [comment]
I also get the same `AssertionError: Control must be added to the page first.`, but it's not crashing on macOS. It just prints in the terminal silently but the app stays open (albeit with no reaction).

**Comment by T0jan** [comment]
Yeah I meant the UI getting unresponsive with  'unrecoverable UI crash'. Program stays open but no no part can be searched anymore.

**Comment by second-string** [comment]
ah I see. my UI is still responsive (as in, buttons still show the hover state if I hover over them, etc). If I switch to a different tab on the left hand column, then switch back, the original tab will work again for another search.

**Comment by T0jan** [comment]
Oh that's true on my systems as well as I just noticed. so there is probably just an update missing after the search is done?

**Review by eeintech — COMMENTED** [review]
Should be all fixed now thanks!

**Pull request merged**
