### PR TITLE
1.0.5

### PR DESCRIPTION
**Pull request by eeintech**
- https://github.com/sparkmicro/Ki-nTree/pull/181
- https://github.com/sparkmicro/Ki-nTree/pull/182
- https://github.com/sparkmicro/Ki-nTree/pull/185
- https://github.com/sparkmicro/Ki-nTree/pull/188
- https://github.com/sparkmicro/Ki-nTree/pull/200

Fixes: https://github.com/sparkmicro/Ki-nTree/issues/191

### CODE REVIEW

**Comment by eeintech** [comment]
@T0jan I think your PR has introduced something weird as alternate resistors are created as new parts in InvenTree when they shouldn't, I didn't get much time to look into it but I can't reproduce it within the GUI. Any ideas?

**Comment by T0jan** [comment]
@eeintech I haven't changed anything involved with the alternate test so it has to be some kind of side effect. lets see if I can find anything. It is very weird, that it works for the capacitor but not for the resistors later, so maybe it is something with the configs, not the code.

**Comment by T0jan** [comment]
@eeintech Ok I found the reason: it is the `Temperature Range` parameter. As we use the stable branch again the parameter check is active by default (#165) and so the parameter gets rejected. For resistors it is part of the compared parameters, for capacitors not so this explains why they act different.

I don't know if it is possible to change the inventree config during the test or in the startup to disable the parameter check.

**Comment by T0jan** [comment]
@eeintech yes there is a conversion, it is the #163 thing which they added for 0.12.0. Inventree by default expects now parameters to be SI-compatible so always something like -50°C, 100mm, 42uF and so on. So a multivalue entry like -55~155°C is not allowed by the server. I told them this is not the best idea so they added a button to be able to switch this off, do you remember?

image

I do not know if it is possible to set this setting via environmental variables in the server setup.

**Comment by eeintech** [comment]
@T0jan I'm sorry, this is new setting completely came out of my mind... just too many things going on right now 😓 

> I do not know if it is possible to unset this setting via environmental variables in the server setup.

Righto I need to follow-up on that... I'm tempted to merge this right now and release `1.0.5` with all the changes then sort this out.
If that setting is enable by default on new and older InvenTree setups, it will cause duplicate resistors to be created (eg. rendering the "Check Existing" toggle useless). What do you think?

**Comment by T0jan** [comment]
@eeintech No worries, I should have written it clear right away, would have saved you the debug time...

I don't think anything speaks against releasing it as is per se, as the setting is documented already it should not cause to much problems for users and not a problem with Ki-nTree. However I would like to patch the error detection for this specific case, so the user gets a clear message if they did not disabled this setting.

> If that setting is enabled by default on new and older InvenTree setups, it will cause duplicate resistors to be created (eg. rendering the "Check Existing" toggle useless). What do you think?

I don't think so. It only gets useless if the setting is not deactivated and the part parameters include a non convertible value. The default case should be the deactivated case where all parameters are generated as before (That's why we added it to the documentation) and there the existing part check will work as before.

**Pull request merged**
