### PR TITLE
datasheet upload, update functionality, pricing

### PR DESCRIPTION
**Pull request by T0jan**
This merge requests fixes a few bugs in unit handling, datasheet download handling and #163 

It also adds three new features (all with user control):

* uploading datasheets to InvenTree, see #162 
* add an update functionality to the alternate mode to add missing parameters, datasheets and images to an existing part
* add the option to use the pricing data of each supplier to create/update price breaks for a supplier part

### CODE REVIEW

**Comment by eeintech** [comment]
Thanks @T0jan. I am really sorry I'm quite swamped right now... I will have to defer to later to check and merge your PR, sorry again!

**Comment by T0jan** [comment]
@eeintech No worries, nothing critical in here, I can use my branch in the meantime. take all the time you need.

**Comment by eeintech** [comment]
Hello @T0jan I was finally able to give it a shot, nice work! I'll merge it now.

I found out there are a lot of incompatibilities which were introduced between InvenTree versions 0.10, 0.11 and 0.12...
I was wondering if you had more bandwidth to try to help fix Ki-nTree to work with `0.12`, the latest InvenTree version?
The `Flet` package is also moving fast and the version used here is getting old in today's standards...

I'm only asking because it seems like you are a power Ki-nTree user with great coding skills and InvenTree experience, which is definitely what the project is in need right now as my time on this project is very limited now unfortunately. 

What do you think?

**Comment by T0jan** [comment]
@eeintech thanks for the merge and the kind words.

You can't image how much boredom you saved me from with Ki-nTree so I would be glad to help you further. However I think `0.12` isn't the best target due to the parameter thing from #165 or do you have an idea how to get around this?

**Comment by eeintech** [comment]
@T0jan Let's find a way to communicate and talk about it. Do you use Discord? I can ask the InvenTree guys to add you there so we can have a channel dedicated to discuss Ki-nTree. Or by email if you prefer?

**Comment by T0jan** [comment]
@eeintech Discord would be great, username there is t0jan.

**Comment by eeintech** [comment]
Cool I added you there

**Pull request merged**
