### PR TITLE
add missing callbacks to live update variables

### PR DESCRIPTION
**Pull request by T0jan**

### CODE REVIEW

**Comment by T0jan** [comment]
@eeintech same thing with the branch here, to avoid conflicts I want to push the changes of the other branch to here once it got merged.

**Comment by eeintech** [comment]
@T0jan I merged #236 so that you can pull `main` here

**Comment by eeintech** [comment]
@T0jan Good to merge?

**Comment by T0jan** [comment]
@eeintech yep

**Pull request merged**
